version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"

  store:
    build:
      context: .
      dockerfile: store-website/Dockerfile
    ports:
      - "3000:3000"
