name: Deploy Store

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Build Docker image
        run: |
          ssh ubuntu@${{ secrets.STORE_IP }} "docker build -t my-store-image -f /home/ubuntu/store-website/Dockerfile /home/ubuntu/store-website"

      - name: Run Docker container
        run: |
          ssh ubuntu@${{ secrets.STORE_IP }} "docker run -d -p 3000:3000 my-store-image"
