name: Deploy Store

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker build -t my-store-image -f store-website/Dockerfile .

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: store-image
          path: store-image.tar

      - name: Deploy to EC2
        uses: appleboy/drone-ssh@v1
        with:
          host: ${{ secrets.STORE_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker load -i store-image.tar
            docker run -d -p 3000:3000 my-store-image
